### ISSUE TITLE
Feature Request: Read files from flash backup

### ISSUE THREAD

**Issue by SciLor** [mon/cc3200tool#4]
It would be nice to be able to read the files from a flash backup.
But this would mean, we would have to completly implement a filesystem parser.

**Comment by mon** [comment]
I definitely won't have time to implement this - I've had a look at some dumps and it's quite a complex format. I *think* I can work out the hashing function from the ROM bootloader I dumped, but it's going to take far too much work.

**Comment by SciLor** [comment]
Implemented read files from flash backup. Using the filetable, not the hashing function (so may fail when the filenames are broken)

https://github.com/toniebox-reverse-engineering/cc3200tool

**Comment by mon** [comment]
Nicely done - not interested in merging back here? I see your branch has a ton of other QOL changes.

**Comment by SciLor** [comment]
Sure I can do that. But currently there are some differences to work out before.
https://github.com/mon/cc3200tool/pull/6

Sidenote: Where the bootloader sits? I may want to implement the filename hashing algorithm to read dumps with broken filenames.

**Comment by mon** [comment]
Might take a little while to get through that diff, but I'll merge it in a week or 2, thanks!

CC3200 ROM can be dumped by reading all memory from 0x00000 to 0x7FFFF. Avoid, inclusively, the gap from 0xB9C to 0xE44. It seems to be secured and will hardfault when read. MCU boots from the address at offset 0x4.

I have some scripts for IDA that can annotate ROM functions and registers, but if you don't use IDA then it's kinda useless to you. The bootloader is quite easy to follow, so it shouldn't be much effort to find the filename hashing function to start reversing it.

**Comment by SciLor** [comment]
The memory address is enough. I already reversed several toniebox cc3200 firmwares with ghidra, so I know where to start.
